metadata:
  name: "No Default Namespace"
  id: "CKV_K8S_MASA_001"
  category: "KUBERNETES"
  severity: "MEDIUM"

definition:
  cond_type: "attribute"
  resource_types:
    - "kubernetes_pod"
    - "kubernetes_deployment"
  attribute: "metadata.labels.xyz-label"
  operator: "exists"
